routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::post('alwaysTrue', function () {
    return response('', 204)
        ->header('Content-Type', 'text/plain');
});

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::match(['get', 'post'], 'documents/pencarian', 'DocumentController@pencarian')->name('pencarian');
Route::get('documents/pemusnahan', 'DocumentController@surat_kadaluarsa')->name('pemusnahan');
Route::get('documents/surat-masuk', 'DocumentController@surat_masuk')->name('surat_masuk');
Route::get('documents/surat-keluar', 'DocumentController@surat_keluar')->name('surat_keluar');
Route::get('documents/peminjaman', 'DocumentController@peminjaman_index')->name('documents.loan.index');
Route::get('documents/peminjaman/{id}', 'DocumentController@peminjaman')->name('documents.loaning');
Route::post('documents/peminjaman/{id}', 'DocumentController@peminjaman_store')->name('documents.loaning.store');
Route::get('documents/classification-list', 'DocumentController@classification_list')->name('documents.classification.all');
Route::post('documents/expunge/{id}', 'DocumentController@pemusnahan')->name('documents.expunge');
Route::resource('documents', 'DocumentController');

Route::resource('documentsDTs', 'DocumentsDTController');

app/Models/DocumentsDT.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class DocumentsDT
 * @package App\Models
 * @version November 28, 2017, 4:47 pm UTC
 *
 * @property string kind
 * @property string nature
 * @property string classification
 * @property string status
 * @property date activestart
 * @property date activestop
 * @property string number
 * @property string ids
 * @property date date
 * @property string from
 * @property string to
 * @property string about
 * @property string summary
 * @property string label
 * @property integer created_by
 * @property string department
 */
class DocumentsDT extends Model
{
    use SoftDeletes;

    public $table = 'dms_documents';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'kind',
        'nature',
        'classification',
        'status',
        'activestart',
        'activestop',
        'number',
        'ids',
        'date',
        'from',
        'to',
        'about',
        'summary',
        'label',
        'created_by',
        'department'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'kind' => 'string',
        'nature' => 'string',
        'classification' => 'string',
        'status' => 'string',
        'activestart' => 'date',
        'activestop' => 'date',
        'number' => 'string',
        'ids' => 'string',
        'date' => 'date',
        'from' => 'string',
        'to' => 'string',
        'about' => 'string',
        'summary' => 'string',
        'label' => 'string',
        'created_by' => 'integer',
        'department' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/DocumentsDTController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\DocumentsDTDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateDocumentsDTRequest;
use App\Http\Requests\UpdateDocumentsDTRequest;
use App\Repositories\DocumentsDTRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class DocumentsDTController extends AppBaseController
{
    /** @var  DocumentsDTRepository */
    private $documentsDTRepository;

    public function __construct(DocumentsDTRepository $documentsDTRepo)
    {
        $this->documentsDTRepository = $documentsDTRepo;
    }

    /**
     * Display a listing of the DocumentsDT.
     *
     * @param DocumentsDTDataTable $documentsDTDataTable
     * @return Response
     */
    public function index(DocumentsDTDataTable $documentsDTDataTable)
    {
        return $documentsDTDataTable->render('documents_d_ts.index');
    }

    /**
     * Show the form for creating a new DocumentsDT.
     *
     * @return Response
     */
    public function create()
    {
        return view('documents_d_ts.create');
    }

    /**
     * Store a newly created DocumentsDT in storage.
     *
     * @param CreateDocumentsDTRequest $request
     *
     * @return Response
     */
    public function store(CreateDocumentsDTRequest $request)
    {
        $input = $request->all();

        $documentsDT = $this->documentsDTRepository->create($input);

        Flash::success('Documents D T saved successfully.');

        return redirect(route('documentsDTs.index'));
    }

    /**
     * Display the specified DocumentsDT.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $documentsDT = $this->documentsDTRepository->findWithoutFail($id);

        if (empty($documentsDT)) {
            Flash::error('Documents D T not found');

            return redirect(route('documentsDTs.index'));
        }

        return view('documents_d_ts.show')->with('documentsDT', $documentsDT);
    }

    /**
     * Show the form for editing the specified DocumentsDT.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $documentsDT = $this->documentsDTRepository->findWithoutFail($id);

        if (empty($documentsDT)) {
            Flash::error('Documents D T not found');

            return redirect(route('documentsDTs.index'));
        }

        return view('documents_d_ts.edit')->with('documentsDT', $documentsDT);
    }

    /**
     * Update the specified DocumentsDT in storage.
     *
     * @param  int              $id
     * @param UpdateDocumentsDTRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateDocumentsDTRequest $request)
    {
        $documentsDT = $this->documentsDTRepository->findWithoutFail($id);

        if (empty($documentsDT)) {
            Flash::error('Documents D T not found');

            return redirect(route('documentsDTs.index'));
        }

        $documentsDT = $this->documentsDTRepository->update($request->all(), $id);

        Flash::success('Documents D T updated successfully.');

        return redirect(route('documentsDTs.index'));
    }

    /**
     * Remove the specified DocumentsDT from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $documentsDT = $this->documentsDTRepository->findWithoutFail($id);

        if (empty($documentsDT)) {
            Flash::error('Documents D T not found');

            return redirect(route('documentsDTs.index'));
        }

        $this->documentsDTRepository->delete($id);

        Flash::success('Documents D T deleted successfully.');

        return redirect(route('documentsDTs.index'));
    }
}

resources/views/documents_d_ts/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Documents D T
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'documentsDTs.store']) !!}

                        @include('documents_d_ts.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/documents_d_ts/datatables_actions.blade.php
{!! Form::open(['route' => ['documentsDTs.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('documentsDTs.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('documentsDTs.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/documents_d_ts/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Documents D T
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($documentsDT, ['route' => ['documentsDTs.update', $documentsDT->id], 'method' => 'patch']) !!}

                        @include('documents_d_ts.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/documents_d_ts/fields.blade.php
<!-- Kind Field -->
<div class="form-group col-sm-6">
    {!! Form::label('kind', 'Kind:') !!}
    {!! Form::text('kind', null, ['class' => 'form-control']) !!}
</div>

<!-- Nature Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nature', 'Nature:') !!}
    {!! Form::text('nature', null, ['class' => 'form-control']) !!}
</div>

<!-- Classification Field -->
<div class="form-group col-sm-6">
    {!! Form::label('classification', 'Classification:') !!}
    {!! Form::text('classification', null, ['class' => 'form-control']) !!}
</div>

<!-- Status Field -->
<div class="form-group col-sm-6">
    {!! Form::label('status', 'Status:') !!}
    {!! Form::text('status', null, ['class' => 'form-control']) !!}
</div>

<!-- Activestart Field -->
<div class="form-group col-sm-6">
    {!! Form::label('activestart', 'Activestart:') !!}
    {!! Form::date('activestart', null, ['class' => 'form-control']) !!}
</div>

<!-- Activestop Field -->
<div class="form-group col-sm-6">
    {!! Form::label('activestop', 'Activestop:') !!}
    {!! Form::date('activestop', null, ['class' => 'form-control']) !!}
</div>

<!-- Number Field -->
<div class="form-group col-sm-6">
    {!! Form::label('number', 'Number:') !!}
    {!! Form::text('number', null, ['class' => 'form-control']) !!}
</div>

<!-- Ids Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ids', 'Ids:') !!}
    {!! Form::text('ids', null, ['class' => 'form-control']) !!}
</div>

<!-- Date Field -->
<div class="form-group col-sm-6">
    {!! Form::label('date', 'Date:') !!}
    {!! Form::date('date', null, ['class' => 'form-control']) !!}
</div>

<!-- From Field -->
<div class="form-group col-sm-6">
    {!! Form::label('from', 'From:') !!}
    {!! Form::text('from', null, ['class' => 'form-control']) !!}
</div>

<!-- To Field -->
<div class="form-group col-sm-6">
    {!! Form::label('to', 'To:') !!}
    {!! Form::text('to', null, ['class' => 'form-control']) !!}
</div>

<!-- About Field -->
<div class="form-group col-sm-6">
    {!! Form::label('about', 'About:') !!}
    {!! Form::text('about', null, ['class' => 'form-control']) !!}
</div>

<!-- Summary Field -->
<div class="form-group col-sm-6">
    {!! Form::label('summary', 'Summary:') !!}
    {!! Form::text('summary', null, ['class' => 'form-control']) !!}
</div>

<!-- Label Field -->
<div class="form-group col-sm-6">
    {!! Form::label('label', 'Label:') !!}
    {!! Form::text('label', null, ['class' => 'form-control']) !!}
</div>

<!-- Created By Field -->
<div class="form-group col-sm-6">
    {!! Form::label('created_by', 'Created By:') !!}
    {!! Form::number('created_by', null, ['class' => 'form-control']) !!}
</div>

<!-- Department Field -->
<div class="form-group col-sm-6">
    {!! Form::label('department', 'Department:') !!}
    {!! Form::text('department', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('documentsDTs.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/documents_d_ts/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Documents D Ts</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('documentsDTs.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('documents_d_ts.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/documents_d_ts/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Documents D T
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('documents_d_ts.show_fields')
                    <a href="{!! route('documentsDTs.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/documents_d_ts/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $documentsDT->id !!}</p>
</div>

<!-- Kind Field -->
<div class="form-group">
    {!! Form::label('kind', 'Kind:') !!}
    <p>{!! $documentsDT->kind !!}</p>
</div>

<!-- Nature Field -->
<div class="form-group">
    {!! Form::label('nature', 'Nature:') !!}
    <p>{!! $documentsDT->nature !!}</p>
</div>

<!-- Classification Field -->
<div class="form-group">
    {!! Form::label('classification', 'Classification:') !!}
    <p>{!! $documentsDT->classification !!}</p>
</div>

<!-- Status Field -->
<div class="form-group">
    {!! Form::label('status', 'Status:') !!}
    <p>{!! $documentsDT->status !!}</p>
</div>

<!-- Activestart Field -->
<div class="form-group">
    {!! Form::label('activestart', 'Activestart:') !!}
    <p>{!! $documentsDT->activestart !!}</p>
</div>

<!-- Activestop Field -->
<div class="form-group">
    {!! Form::label('activestop', 'Activestop:') !!}
    <p>{!! $documentsDT->activestop !!}</p>
</div>

<!-- Number Field -->
<div class="form-group">
    {!! Form::label('number', 'Number:') !!}
    <p>{!! $documentsDT->number !!}</p>
</div>

<!-- Ids Field -->
<div class="form-group">
    {!! Form::label('ids', 'Ids:') !!}
    <p>{!! $documentsDT->ids !!}</p>
</div>

<!-- Date Field -->
<div class="form-group">
    {!! Form::label('date', 'Date:') !!}
    <p>{!! $documentsDT->date !!}</p>
</div>

<!-- From Field -->
<div class="form-group">
    {!! Form::label('from', 'From:') !!}
    <p>{!! $documentsDT->from !!}</p>
</div>

<!-- To Field -->
<div class="form-group">
    {!! Form::label('to', 'To:') !!}
    <p>{!! $documentsDT->to !!}</p>
</div>

<!-- About Field -->
<div class="form-group">
    {!! Form::label('about', 'About:') !!}
    <p>{!! $documentsDT->about !!}</p>
</div>

<!-- Summary Field -->
<div class="form-group">
    {!! Form::label('summary', 'Summary:') !!}
    <p>{!! $documentsDT->summary !!}</p>
</div>

<!-- Label Field -->
<div class="form-group">
    {!! Form::label('label', 'Label:') !!}
    <p>{!! $documentsDT->label !!}</p>
</div>

<!-- Created By Field -->
<div class="form-group">
    {!! Form::label('created_by', 'Created By:') !!}
    <p>{!! $documentsDT->created_by !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $documentsDT->deleted_at !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $documentsDT->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $documentsDT->updated_at !!}</p>
</div>

<!-- Department Field -->
<div class="form-group">
    {!! Form::label('department', 'Department:') !!}
    <p>{!! $documentsDT->department !!}</p>
</div>

resources/views/documents_d_ts/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection